[package]
name = "opentelemetry-zipkin"
version = "0.5.0"
authors = ["OpenTelemetry Authors <cncf-opentelemetry-contributors@lists.cncf.io>"]
description = "Zipkin exporter for OpenTelemetry"
homepage = "https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin"
repository = "https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin"
readme = "README.md"
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["opentelemetry", "zipkin", "tracing", "async"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
http = "0.2"
lazy_static = "1.4.0"
opentelemetry = { version = "0.8.0", path = ".." }
reqwest = { version = "0.10", optional = true }
surf = { version = "2.0", optional = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
typed-builder = "0.5"

[dev-dependencies]
isahc = "0.9"
